// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbINPOU0TEbJv1rQoOoROiDwaqyLAgd-I',
    appId: '1:431014086907:web:b058b3961b6035899f085e',
    messagingSenderId: '431014086907',
    projectId: 'chatbot-ia---smdn',
    authDomain: 'chatbot-ia---smdn.firebaseapp.com',
    storageBucket: 'chatbot-ia---smdn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLY13r5YMnES4ahZeZ5a4koquODZrM5xM',
    appId: '1:431014086907:android:0496302885fbcbe09f085e',
    messagingSenderId: '431014086907',
    projectId: 'chatbot-ia---smdn',
    storageBucket: 'chatbot-ia---smdn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx2MzExIJBSqpIDCZYWkHTIrLHtVSKfDM',
    appId: '1:431014086907:ios:7e5d28da88c254cc9f085e',
    messagingSenderId: '431014086907',
    projectId: 'chatbot-ia---smdn',
    storageBucket: 'chatbot-ia---smdn.firebasestorage.app',
    iosBundleId: 'com.example.branch1',
  );
}
